# Generated by Django 4.1.4 on 2024-01-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cart_price_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='barcode',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.PositiveIntegerField(),
        ),
    ]
