# Generated by Django 4.1.4 on 2024-01-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cart_barcode_alter_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='barcode',
        ),
    ]
