# Generated by Django 4.1.4 on 2024-02-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_cart_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
